Add information reg. out of date screenshots to "ui_screens" folder
corona-warn-app/cwa-documentation pull request #564
Opened 2021-03-22 16:55 UTC by Ein-Tim

This PR adds a markdown file to https://github.com/corona-warn-app/cwa-documentation/tree/master/images/ui_screens which informs that these screenshots are outdated.

Related: #508 

Follow up PR to #559

2021-03-22 17:08 UTC, MikeMcC399 commented on images/ui_screens/Outdated.md
> +Please note that the screenshots in this folder and it's subfolders are outdated.
it's => its

2021-03-22 17:09 UTC, MikeMcC399 requested changes
Grammar comment.

2021-03-22 17:17 UTC, Ein-Tim commented
Thanks.

2021-03-23 13:55 UTC, heinezen approved these changes
LGTM

@dsarkar Please also approve and merge :)

2021-04-06 10:51 UTC, dsarkar approved these changes

2021-04-06 10:51 UTC, merged

2021-04-06 10:52 UTC, dsarkar commented
@Ein-Tim @MikeMcC399 @heinezen Thanks.